services:
  rdfm-server:
    image: antmicro/rdfm-server:latest
    restart: unless-stopped
    environment:
      - RDFM_JWT_SECRET=foobarbaz
      - RDFM_DB_CONNSTRING=sqlite:////database/development.db
      - RDFM_HOSTNAME=rdfm-server
      - RDFM_API_PORT=5000
      - RDFM_DISABLE_ENCRYPTION=1
      - RDFM_DISABLE_API_AUTH=1
      - RDFM_LOCAL_PACKAGE_DIR=/packages/
      - RDFM_STORAGE_DRIVER=s3
      - RDFM_S3_URL=http://minio:9000
      - RDFM_S3_BUCKET=rdfm-packages
      - RDFM_S3_ACCESS_KEY_ID=admin
      - RDFM_S3_ACCESS_SECRET_KEY=admin123
      - RDFM_WSGI_SERVER=werkzeug
    ports:
      - "5000:5000"
    volumes:
      - db:/database/
      - pkgs:/packages/

  minio:
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage:/storage/
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    command: server /storage/

volumes:
  db:
  pkgs:
  storage:

