image: $CI_REGISTRY_IMAGE:rdfm-ci-base

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

cache:
  key: "$CI_PIPELINE_ID"
  paths:
    - device/target/
    - json_schemas/
    - client/
    - server/
    - .cargo/
    - .cache/pip/

.build:
  before_script:
    - ls
    - ls json_schemas
    - |
      if [[ -d device/target ]]; then
        exit 0
      fi
    - apt-get -y install make netcat openssl
    - pip3 install flask
    - . $HOME/.cargo/env
    - cd device
    - cargo build && cargo run --bin rdfm_schema_generator -- --schema-path=../json_schemas/device_schema.json
    - cd ../server
    - poetry build && poetry install
    - pip3 install -e .
    - cd ../client
    - poetry build && poetry install
    - pip3 install -e .
    - cd ..

stages:
  - build
  - code-check
  - local-tests

build:
  extends: .build
  stage: build
  script:
    - echo "Build finished"

python-formatting:
  extends: .build
  stage: code-check
  script:
    - cd server
    - poetry run test
    - cd ../client
    - poetry run test
    - cd ..
  only:
    refs:
      - merge_requests
      - main

rust-formatting:
  extends: .build
  stage: code-check
  script:
    - cd device
    - cargo fmt --all -- --check
    - cd ..
  only:
    refs:
      - merge_requests
      - main

test-arguments:
  extends: .build
  stage: local-tests
  script:
    - python3 tests/test-arguments.py
  only:
    refs:
      - merge_requests
      - main

test-list-devices:
  extends: .build
  stage: local-tests
  script:
    - python3 tests/test-list-devices.py
  only:
    refs:
      - merge_requests
      - main

test-proxy:
  extends: .build
  stage: local-tests
  script:
    - python3 tests/test-proxy.py
  only:
    refs:
      - merge_requests
      - main

test-metadata:
  extends: .build
  stage: local-tests
  script:
    - python3 tests/test-metadata.py
  only:
    refs:
      - merge_requests
      - main

test-crash-client-input:
  extends: .build
  stage: local-tests
  script:
    - apt-get install telnet
    - python3 tests/test-crash-client-input.py
  only:
    refs:
      - merge_requests
      - main
      
