image: python:3.10-alpine
before_script:
  - pip install -r requirements.txt

stages:
  - local-tests

test-arguments:
  stage: local-tests
  script:
    - python3 tests/test-arguments.py

test-list-devices:
  stage: local-tests
  script:
    - python3 tests/test-list-devices.py

test-proxy:
  stage: local-tests
  script:
    - python3 tests/test-proxy.py

test-metadata:
  stage: local-tests
  script:
    - python3 tests/test-metadata.py
