image: python:3.10-alpine
before_script:
  - apk add --no-cache gcc musl-dev curl
  - curl https://sh.rustup.rs -sSf | ash -s -- -y
  - source $HOME/.cargo/env
  - pip install -r requirements.txt
  - cd device
  - cargo build && cargo run --bin rdfm-schema-generator -- --schema-path=../json_schemas/device_schema.json
  - cd ..

stages:
  - code-check
  - local-tests

check-formatting:
  stage: code-check
  script:
    - for f in *.py; do python3 -m pycodestyle "$f"; done
    - cd device
    - cargo fmt --all -- --check
    - cd ..

check-typing:
  stage: code-check
  script:
    - for f in *.py; do python3 -m mypy "$f"; done

test-arguments:
  stage: local-tests
  script:
    - python3 tests/test-arguments.py

test-list-devices:
  stage: local-tests
  script:
    - python3 tests/test-list-devices.py

test-proxy:
  stage: local-tests
  script:
    - python3 tests/test-proxy.py

test-metadata:
  stage: local-tests
  script:
    - python3 tests/test-metadata.py

  
test-crash-client-input:
  stage: local-tests
  script:
    - python3 tests/test-crash-client-input.py