[tool.poetry]
name = "rdfm-mgmt-server"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [
    { include = "rdfm_mgmt_server.py", from = "src" },
    { include = "proxy.py", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.10"
jsonschema = "^4.17.3"
rdfm_mgmt_communication = {path = "../common/communication"}

[tool.poetry.group.test.dependencies]
mypy = "^1.4.0"
types-jsonschema = "^4.17.0.8"
pycodestyle = "^2.10.0"


[tool.poetry.group.types.dependencies]
types-flask = "^1.1.6"
[tool.poetry.scripts]
test = 'scripts:static_checks'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[mypy]
plugins = [
    "pydantic.mypy"
]
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true
